---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dns.ch1aki.github.io
  resources:
  - owners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.ch1aki.github.io
  resources:
  - owners/finalizers
  verbs:
  - update
- apiGroups:
  - dns.ch1aki.github.io
  resources:
  - owners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dns.ch1aki.github.io
  resources:
  - providers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.ch1aki.github.io
  resources:
  - providers/finalizers
  verbs:
  - update
- apiGroups:
  - dns.ch1aki.github.io
  resources:
  - providers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dns.ch1aki.github.io
  resources:
  - resourcerecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.ch1aki.github.io
  resources:
  - resourcerecords/finalizers
  verbs:
  - update
- apiGroups:
  - dns.ch1aki.github.io
  resources:
  - resourcerecords/status
  verbs:
  - get
  - patch
  - update
