apiVersion: dns.ch1aki.github.io/v1alpha1
kind: Provider
metadata:
  labels:
    app.kubernetes.io/name: provider
    app.kubernetes.io/instance: provider-sample
    app.kubernetes.io/part-of: dns-rr
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dns-rr
  name: provider-sample
spec:
  route53:
    hostedZoneID: Z07391882VV0BXW4CMCYV
    hostedZoneName: ch1aki.com
    region: ap-northeast-1
    auth:
      secretRef:
        accessKeyIDSecretRef:
          name: aws-private
          key: accessKeyId
        secretAccessKeySecretRef:
          name: aws-private
          key: secretAccessKey